# Generated by Django 5.1.2 on 2024-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('due_date', models.DateTimeField(blank=True, verbose_name='due by: ')),
                ('priority', models.IntegerField(choices=[(1, 'Important'), (2, 'Normal'), (3, 'Lowprio')], default=2)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
