# Generated by Django 5.1.2 on 2024-10-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_List', '0002_alter_task_due_date_alter_task_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'work'), ('Family', 'family'), ('Personal', 'personal'), ('Other', 'other')], default='Other', max_length=20),
        ),
    ]
